// Fixture oficial del Mundial 2026 (sorteo del 5/12/2025).
// Fechas, horarios (UTC) y sedes verificados con el calendario oficial FIFA.
// IDs de grupos conservados (mismo cruce de equipos); en eliminatorias el ID
// coincide con el número de partido oficial FIFA (match-073 = Partido 73).

export const GROUPS = {
  "A": [
    "México",
    "Sudáfrica",
    "Corea del Sur",
    "República Checa"
  ],
  "B": [
    "Canadá",
    "Bosnia y Herzegovina",
    "Qatar",
    "Suiza"
  ],
  "C": [
    "Brasil",
    "Marruecos",
    "Haití",
    "Escocia"
  ],
  "D": [
    "Estados Unidos",
    "Paraguay",
    "Australia",
    "Turquía"
  ],
  "E": [
    "Alemania",
    "Curazao",
    "Costa de Marfil",
    "Ecuador"
  ],
  "F": [
    "Países Bajos",
    "Japón",
    "Suecia",
    "Túnez"
  ],
  "G": [
    "Bélgica",
    "Egipto",
    "Irán",
    "Nueva Zelanda"
  ],
  "H": [
    "España",
    "Cabo Verde",
    "Arabia Saudita",
    "Uruguay"
  ],
  "I": [
    "Francia",
    "Senegal",
    "Irak",
    "Noruega"
  ],
  "J": [
    "Argentina",
    "Argelia",
    "Austria",
    "Jordania"
  ],
  "K": [
    "Portugal",
    "RD Congo",
    "Uzbekistán",
    "Colombia"
  ],
  "L": [
    "Inglaterra",
    "Croacia",
    "Ghana",
    "Panamá"
  ]
};

export const MATCHES = [
  {
    "id": "match-001",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-11",
    "datetime": "2026-06-11T19:00:00Z",
    "venue": "Estadio Azteca, Ciudad de México",
    "home": "México",
    "away": "Sudáfrica",
    "homeRaw": "Mexico",
    "awayRaw": "South Africa"
  },
  {
    "id": "match-002",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-11",
    "datetime": "2026-06-12T02:00:00Z",
    "venue": "Estadio Akron, Guadalajara",
    "home": "Corea del Sur",
    "away": "República Checa",
    "homeRaw": "South Korea",
    "awayRaw": "Czech Republic"
  },
  {
    "id": "match-003",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-12",
    "datetime": "2026-06-12T19:00:00Z",
    "venue": "BMO Field, Toronto",
    "home": "Canadá",
    "away": "Bosnia y Herzegovina",
    "homeRaw": "Canada",
    "awayRaw": "Bosnia and Herzegovina"
  },
  {
    "id": "match-004",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-13",
    "datetime": "2026-06-13T19:00:00Z",
    "venue": "Levi's Stadium, San Francisco",
    "home": "Qatar",
    "away": "Suiza",
    "homeRaw": "Qatar",
    "awayRaw": "Switzerland"
  },
  {
    "id": "match-005",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-12",
    "datetime": "2026-06-13T01:00:00Z",
    "venue": "SoFi Stadium, Los Ángeles",
    "home": "Estados Unidos",
    "away": "Paraguay",
    "homeRaw": "United States",
    "awayRaw": "Paraguay"
  },
  {
    "id": "match-006",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-13",
    "datetime": "2026-06-14T04:00:00Z",
    "venue": "BC Place, Vancouver",
    "home": "Australia",
    "away": "Turquía",
    "homeRaw": "Australia",
    "awayRaw": "Turkey"
  },
  {
    "id": "match-007",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-13",
    "datetime": "2026-06-13T22:00:00Z",
    "venue": "MetLife Stadium, Nueva York/NJ",
    "home": "Brasil",
    "away": "Marruecos",
    "homeRaw": "Brazil",
    "awayRaw": "Morocco"
  },
  {
    "id": "match-008",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-13",
    "datetime": "2026-06-14T01:00:00Z",
    "venue": "Gillette Stadium, Boston",
    "home": "Haití",
    "away": "Escocia",
    "homeRaw": "Haiti",
    "awayRaw": "Scotland"
  },
  {
    "id": "match-009",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-14",
    "datetime": "2026-06-14T17:00:00Z",
    "venue": "NRG Stadium, Houston",
    "home": "Alemania",
    "away": "Curazao",
    "homeRaw": "Germany",
    "awayRaw": "Curacao"
  },
  {
    "id": "match-010",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-14",
    "datetime": "2026-06-14T23:00:00Z",
    "venue": "Lincoln Financial Field, Filadelfia",
    "home": "Costa de Marfil",
    "away": "Ecuador",
    "homeRaw": "Ivory Coast",
    "awayRaw": "Ecuador"
  },
  {
    "id": "match-011",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-14",
    "datetime": "2026-06-14T20:00:00Z",
    "venue": "AT&T Stadium, Dallas",
    "home": "Países Bajos",
    "away": "Japón",
    "homeRaw": "Netherlands",
    "awayRaw": "Japan"
  },
  {
    "id": "match-012",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-14",
    "datetime": "2026-06-15T02:00:00Z",
    "venue": "Estadio BBVA, Monterrey",
    "home": "Suecia",
    "away": "Túnez",
    "homeRaw": "Sweden",
    "awayRaw": "Tunisia"
  },
  {
    "id": "match-013",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-15",
    "datetime": "2026-06-15T19:00:00Z",
    "venue": "Lumen Field, Seattle",
    "home": "Bélgica",
    "away": "Egipto",
    "homeRaw": "Belgium",
    "awayRaw": "Egypt"
  },
  {
    "id": "match-014",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-15",
    "datetime": "2026-06-16T01:00:00Z",
    "venue": "SoFi Stadium, Los Ángeles",
    "home": "Irán",
    "away": "Nueva Zelanda",
    "homeRaw": "Iran",
    "awayRaw": "New Zealand"
  },
  {
    "id": "match-015",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-15",
    "datetime": "2026-06-15T16:00:00Z",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "home": "España",
    "away": "Cabo Verde",
    "homeRaw": "Spain",
    "awayRaw": "Cape Verde"
  },
  {
    "id": "match-016",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-15",
    "datetime": "2026-06-15T22:00:00Z",
    "venue": "Hard Rock Stadium, Miami",
    "home": "Arabia Saudita",
    "away": "Uruguay",
    "homeRaw": "Saudi Arabia",
    "awayRaw": "Uruguay"
  },
  {
    "id": "match-017",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-16",
    "datetime": "2026-06-16T19:00:00Z",
    "venue": "MetLife Stadium, Nueva York/NJ",
    "home": "Francia",
    "away": "Senegal",
    "homeRaw": "France",
    "awayRaw": "Senegal"
  },
  {
    "id": "match-018",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-16",
    "datetime": "2026-06-16T22:00:00Z",
    "venue": "Gillette Stadium, Boston",
    "home": "Irak",
    "away": "Noruega",
    "homeRaw": "Iraq",
    "awayRaw": "Norway"
  },
  {
    "id": "match-019",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-16",
    "datetime": "2026-06-17T01:00:00Z",
    "venue": "Arrowhead Stadium, Kansas City",
    "home": "Argentina",
    "away": "Argelia",
    "homeRaw": "Argentina",
    "awayRaw": "Algeria"
  },
  {
    "id": "match-020",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-16",
    "datetime": "2026-06-17T04:00:00Z",
    "venue": "Levi's Stadium, San Francisco",
    "home": "Austria",
    "away": "Jordania",
    "homeRaw": "Austria",
    "awayRaw": "Jordan"
  },
  {
    "id": "match-021",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-17",
    "datetime": "2026-06-17T17:00:00Z",
    "venue": "NRG Stadium, Houston",
    "home": "Portugal",
    "away": "RD Congo",
    "homeRaw": "Portugal",
    "awayRaw": "DR Congo"
  },
  {
    "id": "match-022",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-17",
    "datetime": "2026-06-18T02:00:00Z",
    "venue": "Estadio Azteca, Ciudad de México",
    "home": "Uzbekistán",
    "away": "Colombia",
    "homeRaw": "Uzbekistan",
    "awayRaw": "Colombia"
  },
  {
    "id": "match-023",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-17",
    "datetime": "2026-06-17T20:00:00Z",
    "venue": "AT&T Stadium, Dallas",
    "home": "Inglaterra",
    "away": "Croacia",
    "homeRaw": "England",
    "awayRaw": "Croatia"
  },
  {
    "id": "match-024",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-17",
    "datetime": "2026-06-17T23:00:00Z",
    "venue": "BMO Field, Toronto",
    "home": "Ghana",
    "away": "Panamá",
    "homeRaw": "Ghana",
    "awayRaw": "Panama"
  },
  {
    "id": "match-025",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-18",
    "datetime": "2026-06-19T01:00:00Z",
    "venue": "Estadio Akron, Guadalajara",
    "home": "México",
    "away": "Corea del Sur",
    "homeRaw": "Mexico",
    "awayRaw": "South Korea"
  },
  {
    "id": "match-026",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-18",
    "datetime": "2026-06-18T16:00:00Z",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "home": "República Checa",
    "away": "Sudáfrica",
    "homeRaw": "Czech Republic",
    "awayRaw": "South Africa"
  },
  {
    "id": "match-027",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-18",
    "datetime": "2026-06-18T22:00:00Z",
    "venue": "BC Place, Vancouver",
    "home": "Canadá",
    "away": "Qatar",
    "homeRaw": "Canada",
    "awayRaw": "Qatar"
  },
  {
    "id": "match-028",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-18",
    "datetime": "2026-06-18T19:00:00Z",
    "venue": "SoFi Stadium, Los Ángeles",
    "home": "Suiza",
    "away": "Bosnia y Herzegovina",
    "homeRaw": "Switzerland",
    "awayRaw": "Bosnia and Herzegovina"
  },
  {
    "id": "match-029",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-19",
    "datetime": "2026-06-20T01:00:00Z",
    "venue": "Lincoln Financial Field, Filadelfia",
    "home": "Brasil",
    "away": "Haití",
    "homeRaw": "Brazil",
    "awayRaw": "Haiti"
  },
  {
    "id": "match-030",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-19",
    "datetime": "2026-06-19T22:00:00Z",
    "venue": "Gillette Stadium, Boston",
    "home": "Escocia",
    "away": "Marruecos",
    "homeRaw": "Scotland",
    "awayRaw": "Morocco"
  },
  {
    "id": "match-031",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-19",
    "datetime": "2026-06-19T19:00:00Z",
    "venue": "Lumen Field, Seattle",
    "home": "Estados Unidos",
    "away": "Australia",
    "homeRaw": "United States",
    "awayRaw": "Australia"
  },
  {
    "id": "match-032",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-19",
    "datetime": "2026-06-20T03:00:00Z",
    "venue": "Levi's Stadium, San Francisco",
    "home": "Turquía",
    "away": "Paraguay",
    "homeRaw": "Turkey",
    "awayRaw": "Paraguay"
  },
  {
    "id": "match-033",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-20",
    "datetime": "2026-06-20T20:00:00Z",
    "venue": "BMO Field, Toronto",
    "home": "Alemania",
    "away": "Costa de Marfil",
    "homeRaw": "Germany",
    "awayRaw": "Ivory Coast"
  },
  {
    "id": "match-034",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-20",
    "datetime": "2026-06-21T00:00:00Z",
    "venue": "Arrowhead Stadium, Kansas City",
    "home": "Ecuador",
    "away": "Curazao",
    "homeRaw": "Ecuador",
    "awayRaw": "Curacao"
  },
  {
    "id": "match-035",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-20",
    "datetime": "2026-06-20T17:00:00Z",
    "venue": "NRG Stadium, Houston",
    "home": "Países Bajos",
    "away": "Suecia",
    "homeRaw": "Netherlands",
    "awayRaw": "Sweden"
  },
  {
    "id": "match-036",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-20",
    "datetime": "2026-06-21T04:00:00Z",
    "venue": "Estadio BBVA, Monterrey",
    "home": "Túnez",
    "away": "Japón",
    "homeRaw": "Tunisia",
    "awayRaw": "Japan"
  },
  {
    "id": "match-037",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-21",
    "datetime": "2026-06-21T19:00:00Z",
    "venue": "SoFi Stadium, Los Ángeles",
    "home": "Bélgica",
    "away": "Irán",
    "homeRaw": "Belgium",
    "awayRaw": "Iran"
  },
  {
    "id": "match-038",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-21",
    "datetime": "2026-06-22T01:00:00Z",
    "venue": "BC Place, Vancouver",
    "home": "Nueva Zelanda",
    "away": "Egipto",
    "homeRaw": "New Zealand",
    "awayRaw": "Egypt"
  },
  {
    "id": "match-039",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-21",
    "datetime": "2026-06-21T16:00:00Z",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "home": "España",
    "away": "Arabia Saudita",
    "homeRaw": "Spain",
    "awayRaw": "Saudi Arabia"
  },
  {
    "id": "match-040",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-21",
    "datetime": "2026-06-21T22:00:00Z",
    "venue": "Hard Rock Stadium, Miami",
    "home": "Uruguay",
    "away": "Cabo Verde",
    "homeRaw": "Uruguay",
    "awayRaw": "Cape Verde"
  },
  {
    "id": "match-041",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-22",
    "datetime": "2026-06-22T21:00:00Z",
    "venue": "Lincoln Financial Field, Filadelfia",
    "home": "Francia",
    "away": "Irak",
    "homeRaw": "France",
    "awayRaw": "Iraq"
  },
  {
    "id": "match-042",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-22",
    "datetime": "2026-06-23T00:00:00Z",
    "venue": "MetLife Stadium, Nueva York/NJ",
    "home": "Noruega",
    "away": "Senegal",
    "homeRaw": "Norway",
    "awayRaw": "Senegal"
  },
  {
    "id": "match-043",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-22",
    "datetime": "2026-06-22T17:00:00Z",
    "venue": "AT&T Stadium, Dallas",
    "home": "Argentina",
    "away": "Austria",
    "homeRaw": "Argentina",
    "awayRaw": "Austria"
  },
  {
    "id": "match-044",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-22",
    "datetime": "2026-06-23T03:00:00Z",
    "venue": "Levi's Stadium, San Francisco",
    "home": "Jordania",
    "away": "Argelia",
    "homeRaw": "Jordan",
    "awayRaw": "Algeria"
  },
  {
    "id": "match-045",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-23",
    "datetime": "2026-06-23T17:00:00Z",
    "venue": "NRG Stadium, Houston",
    "home": "Portugal",
    "away": "Uzbekistán",
    "homeRaw": "Portugal",
    "awayRaw": "Uzbekistan"
  },
  {
    "id": "match-046",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-23",
    "datetime": "2026-06-24T02:00:00Z",
    "venue": "Estadio Akron, Guadalajara",
    "home": "Colombia",
    "away": "RD Congo",
    "homeRaw": "Colombia",
    "awayRaw": "DR Congo"
  },
  {
    "id": "match-047",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-23",
    "datetime": "2026-06-23T20:00:00Z",
    "venue": "Gillette Stadium, Boston",
    "home": "Inglaterra",
    "away": "Ghana",
    "homeRaw": "England",
    "awayRaw": "Ghana"
  },
  {
    "id": "match-048",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-23",
    "datetime": "2026-06-23T23:00:00Z",
    "venue": "BMO Field, Toronto",
    "home": "Panamá",
    "away": "Croacia",
    "homeRaw": "Panama",
    "awayRaw": "Croatia"
  },
  {
    "id": "match-049",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-24",
    "datetime": "2026-06-25T01:00:00Z",
    "venue": "Estadio Azteca, Ciudad de México",
    "home": "República Checa",
    "away": "México",
    "homeRaw": "Czech Republic",
    "awayRaw": "Mexico"
  },
  {
    "id": "match-050",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-24",
    "datetime": "2026-06-25T01:00:00Z",
    "venue": "Estadio BBVA, Monterrey",
    "home": "Sudáfrica",
    "away": "Corea del Sur",
    "homeRaw": "South Africa",
    "awayRaw": "South Korea"
  },
  {
    "id": "match-051",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-24",
    "datetime": "2026-06-24T19:00:00Z",
    "venue": "BC Place, Vancouver",
    "home": "Suiza",
    "away": "Canadá",
    "homeRaw": "Switzerland",
    "awayRaw": "Canada"
  },
  {
    "id": "match-052",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-24",
    "datetime": "2026-06-24T19:00:00Z",
    "venue": "Lumen Field, Seattle",
    "home": "Bosnia y Herzegovina",
    "away": "Qatar",
    "homeRaw": "Bosnia and Herzegovina",
    "awayRaw": "Qatar"
  },
  {
    "id": "match-053",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-24",
    "datetime": "2026-06-24T22:00:00Z",
    "venue": "Hard Rock Stadium, Miami",
    "home": "Escocia",
    "away": "Brasil",
    "homeRaw": "Scotland",
    "awayRaw": "Brazil"
  },
  {
    "id": "match-054",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-24",
    "datetime": "2026-06-24T22:00:00Z",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "home": "Marruecos",
    "away": "Haití",
    "homeRaw": "Morocco",
    "awayRaw": "Haiti"
  },
  {
    "id": "match-055",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-25",
    "datetime": "2026-06-26T02:00:00Z",
    "venue": "SoFi Stadium, Los Ángeles",
    "home": "Turquía",
    "away": "Estados Unidos",
    "homeRaw": "Turkey",
    "awayRaw": "United States"
  },
  {
    "id": "match-056",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-25",
    "datetime": "2026-06-26T02:00:00Z",
    "venue": "Levi's Stadium, San Francisco",
    "home": "Paraguay",
    "away": "Australia",
    "homeRaw": "Paraguay",
    "awayRaw": "Australia"
  },
  {
    "id": "match-057",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-25",
    "datetime": "2026-06-25T20:00:00Z",
    "venue": "MetLife Stadium, Nueva York/NJ",
    "home": "Ecuador",
    "away": "Alemania",
    "homeRaw": "Ecuador",
    "awayRaw": "Germany"
  },
  {
    "id": "match-058",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-25",
    "datetime": "2026-06-25T20:00:00Z",
    "venue": "Lincoln Financial Field, Filadelfia",
    "home": "Curazao",
    "away": "Costa de Marfil",
    "homeRaw": "Curacao",
    "awayRaw": "Ivory Coast"
  },
  {
    "id": "match-059",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-25",
    "datetime": "2026-06-25T23:00:00Z",
    "venue": "Arrowhead Stadium, Kansas City",
    "home": "Túnez",
    "away": "Países Bajos",
    "homeRaw": "Tunisia",
    "awayRaw": "Netherlands"
  },
  {
    "id": "match-060",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-25",
    "datetime": "2026-06-25T23:00:00Z",
    "venue": "AT&T Stadium, Dallas",
    "home": "Japón",
    "away": "Suecia",
    "homeRaw": "Japan",
    "awayRaw": "Sweden"
  },
  {
    "id": "match-061",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-26",
    "datetime": "2026-06-27T03:00:00Z",
    "venue": "BC Place, Vancouver",
    "home": "Nueva Zelanda",
    "away": "Bélgica",
    "homeRaw": "New Zealand",
    "awayRaw": "Belgium"
  },
  {
    "id": "match-062",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-26",
    "datetime": "2026-06-27T03:00:00Z",
    "venue": "Lumen Field, Seattle",
    "home": "Egipto",
    "away": "Irán",
    "homeRaw": "Egypt",
    "awayRaw": "Iran"
  },
  {
    "id": "match-063",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-26",
    "datetime": "2026-06-27T00:00:00Z",
    "venue": "Estadio Akron, Guadalajara",
    "home": "Uruguay",
    "away": "España",
    "homeRaw": "Uruguay",
    "awayRaw": "Spain"
  },
  {
    "id": "match-064",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-26",
    "datetime": "2026-06-27T00:00:00Z",
    "venue": "NRG Stadium, Houston",
    "home": "Cabo Verde",
    "away": "Arabia Saudita",
    "homeRaw": "Cape Verde",
    "awayRaw": "Saudi Arabia"
  },
  {
    "id": "match-065",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-26",
    "datetime": "2026-06-26T19:00:00Z",
    "venue": "Gillette Stadium, Boston",
    "home": "Noruega",
    "away": "Francia",
    "homeRaw": "Norway",
    "awayRaw": "France"
  },
  {
    "id": "match-066",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-26",
    "datetime": "2026-06-26T19:00:00Z",
    "venue": "BMO Field, Toronto",
    "home": "Senegal",
    "away": "Irak",
    "homeRaw": "Senegal",
    "awayRaw": "Iraq"
  },
  {
    "id": "match-067",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-27",
    "datetime": "2026-06-28T02:00:00Z",
    "venue": "AT&T Stadium, Dallas",
    "home": "Jordania",
    "away": "Argentina",
    "homeRaw": "Jordan",
    "awayRaw": "Argentina"
  },
  {
    "id": "match-068",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-27",
    "datetime": "2026-06-28T02:00:00Z",
    "venue": "Arrowhead Stadium, Kansas City",
    "home": "Argelia",
    "away": "Austria",
    "homeRaw": "Algeria",
    "awayRaw": "Austria"
  },
  {
    "id": "match-069",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-27",
    "datetime": "2026-06-27T23:30:00Z",
    "venue": "Hard Rock Stadium, Miami",
    "home": "Colombia",
    "away": "Portugal",
    "homeRaw": "Colombia",
    "awayRaw": "Portugal"
  },
  {
    "id": "match-070",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-27",
    "datetime": "2026-06-27T23:30:00Z",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "home": "RD Congo",
    "away": "Uzbekistán",
    "homeRaw": "DR Congo",
    "awayRaw": "Uzbekistan"
  },
  {
    "id": "match-071",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-27",
    "datetime": "2026-06-27T21:00:00Z",
    "venue": "MetLife Stadium, Nueva York/NJ",
    "home": "Panamá",
    "away": "Inglaterra",
    "homeRaw": "Panama",
    "awayRaw": "England"
  },
  {
    "id": "match-072",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-27",
    "datetime": "2026-06-27T21:00:00Z",
    "venue": "Lincoln Financial Field, Filadelfia",
    "home": "Croacia",
    "away": "Ghana",
    "homeRaw": "Croatia",
    "awayRaw": "Ghana"
  },
  {
    "id": "match-073",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-28",
    "datetime": "2026-06-28T19:00:00Z",
    "venue": "SoFi Stadium, Los Ángeles",
    "home": "2° Grupo A",
    "away": "2° Grupo B",
    "homeRaw": "Runner-up Group A",
    "awayRaw": "Runner-up Group B"
  },
  {
    "id": "match-074",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-29",
    "datetime": "2026-06-29T20:30:00Z",
    "venue": "Gillette Stadium, Boston",
    "home": "1° Grupo E",
    "away": "Mejor 3° (A/B/C/D/F)",
    "homeRaw": "Winner Group E",
    "awayRaw": "Third Group A/B/C/D/F"
  },
  {
    "id": "match-075",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-29",
    "datetime": "2026-06-30T01:00:00Z",
    "venue": "Estadio BBVA, Monterrey",
    "home": "1° Grupo F",
    "away": "2° Grupo C",
    "homeRaw": "Winner Group F",
    "awayRaw": "Runner-up Group C"
  },
  {
    "id": "match-076",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-29",
    "datetime": "2026-06-29T17:00:00Z",
    "venue": "NRG Stadium, Houston",
    "home": "1° Grupo C",
    "away": "2° Grupo F",
    "homeRaw": "Winner Group C",
    "awayRaw": "Runner-up Group F"
  },
  {
    "id": "match-077",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-30",
    "datetime": "2026-06-30T21:00:00Z",
    "venue": "MetLife Stadium, Nueva York/NJ",
    "home": "1° Grupo I",
    "away": "Mejor 3° (C/D/F/G/H)",
    "homeRaw": "Winner Group I",
    "awayRaw": "Third Group C/D/F/G/H"
  },
  {
    "id": "match-078",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-30",
    "datetime": "2026-06-30T17:00:00Z",
    "venue": "AT&T Stadium, Dallas",
    "home": "2° Grupo E",
    "away": "2° Grupo I",
    "homeRaw": "Runner-up Group E",
    "awayRaw": "Runner-up Group I"
  },
  {
    "id": "match-079",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-30",
    "datetime": "2026-07-01T01:00:00Z",
    "venue": "Estadio Azteca, Ciudad de México",
    "home": "1° Grupo A",
    "away": "Mejor 3° (C/E/F/H/I)",
    "homeRaw": "Winner Group A",
    "awayRaw": "Third Group C/E/F/H/I"
  },
  {
    "id": "match-080",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-01",
    "datetime": "2026-07-01T16:00:00Z",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "home": "1° Grupo L",
    "away": "Mejor 3° (E/H/I/J/K)",
    "homeRaw": "Winner Group L",
    "awayRaw": "Third Group E/H/I/J/K"
  },
  {
    "id": "match-081",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-01",
    "datetime": "2026-07-02T00:00:00Z",
    "venue": "Levi's Stadium, San Francisco",
    "home": "1° Grupo D",
    "away": "Mejor 3° (B/E/F/I/J)",
    "homeRaw": "Winner Group D",
    "awayRaw": "Third Group B/E/F/I/J"
  },
  {
    "id": "match-082",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-01",
    "datetime": "2026-07-01T20:00:00Z",
    "venue": "Lumen Field, Seattle",
    "home": "1° Grupo G",
    "away": "Mejor 3° (A/E/H/I/J)",
    "homeRaw": "Winner Group G",
    "awayRaw": "Third Group A/E/H/I/J"
  },
  {
    "id": "match-083",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-02",
    "datetime": "2026-07-02T23:00:00Z",
    "venue": "BMO Field, Toronto",
    "home": "2° Grupo K",
    "away": "2° Grupo L",
    "homeRaw": "Runner-up Group K",
    "awayRaw": "Runner-up Group L"
  },
  {
    "id": "match-084",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-02",
    "datetime": "2026-07-02T19:00:00Z",
    "venue": "SoFi Stadium, Los Ángeles",
    "home": "1° Grupo H",
    "away": "2° Grupo J",
    "homeRaw": "Winner Group H",
    "awayRaw": "Runner-up Group J"
  },
  {
    "id": "match-085",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-02",
    "datetime": "2026-07-03T03:00:00Z",
    "venue": "BC Place, Vancouver",
    "home": "1° Grupo B",
    "away": "Mejor 3° (E/F/G/I/J)",
    "homeRaw": "Winner Group B",
    "awayRaw": "Third Group E/F/G/I/J"
  },
  {
    "id": "match-086",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-03",
    "datetime": "2026-07-03T22:00:00Z",
    "venue": "Hard Rock Stadium, Miami",
    "home": "1° Grupo J",
    "away": "2° Grupo H",
    "homeRaw": "Winner Group J",
    "awayRaw": "Runner-up Group H"
  },
  {
    "id": "match-087",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-03",
    "datetime": "2026-07-04T01:30:00Z",
    "venue": "Arrowhead Stadium, Kansas City",
    "home": "1° Grupo K",
    "away": "Mejor 3° (D/E/I/J/L)",
    "homeRaw": "Winner Group K",
    "awayRaw": "Third Group D/E/I/J/L"
  },
  {
    "id": "match-088",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-03",
    "datetime": "2026-07-03T18:00:00Z",
    "venue": "AT&T Stadium, Dallas",
    "home": "2° Grupo D",
    "away": "2° Grupo G",
    "homeRaw": "Runner-up Group D",
    "awayRaw": "Runner-up Group G"
  },
  {
    "id": "match-089",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-04",
    "datetime": "2026-07-04T21:00:00Z",
    "venue": "Lincoln Financial Field, Filadelfia",
    "home": "Ganador partido 74",
    "away": "Ganador partido 77",
    "homeRaw": "Winner Match 74",
    "awayRaw": "Winner Match 77"
  },
  {
    "id": "match-090",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-04",
    "datetime": "2026-07-04T17:00:00Z",
    "venue": "NRG Stadium, Houston",
    "home": "Ganador partido 73",
    "away": "Ganador partido 75",
    "homeRaw": "Winner Match 73",
    "awayRaw": "Winner Match 75"
  },
  {
    "id": "match-091",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-05",
    "datetime": "2026-07-05T20:00:00Z",
    "venue": "MetLife Stadium, Nueva York/NJ",
    "home": "Ganador partido 76",
    "away": "Ganador partido 78",
    "homeRaw": "Winner Match 76",
    "awayRaw": "Winner Match 78"
  },
  {
    "id": "match-092",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-05",
    "datetime": "2026-07-06T00:00:00Z",
    "venue": "Estadio Azteca, Ciudad de México",
    "home": "Ganador partido 79",
    "away": "Ganador partido 80",
    "homeRaw": "Winner Match 79",
    "awayRaw": "Winner Match 80"
  },
  {
    "id": "match-093",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-06",
    "datetime": "2026-07-06T19:00:00Z",
    "venue": "AT&T Stadium, Dallas",
    "home": "Ganador partido 83",
    "away": "Ganador partido 84",
    "homeRaw": "Winner Match 83",
    "awayRaw": "Winner Match 84"
  },
  {
    "id": "match-094",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-06",
    "datetime": "2026-07-07T00:00:00Z",
    "venue": "Lumen Field, Seattle",
    "home": "Ganador partido 81",
    "away": "Ganador partido 82",
    "homeRaw": "Winner Match 81",
    "awayRaw": "Winner Match 82"
  },
  {
    "id": "match-095",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-07",
    "datetime": "2026-07-07T16:00:00Z",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "home": "Ganador partido 86",
    "away": "Ganador partido 88",
    "homeRaw": "Winner Match 86",
    "awayRaw": "Winner Match 88"
  },
  {
    "id": "match-096",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-07",
    "datetime": "2026-07-07T20:00:00Z",
    "venue": "BC Place, Vancouver",
    "home": "Ganador partido 85",
    "away": "Ganador partido 87",
    "homeRaw": "Winner Match 85",
    "awayRaw": "Winner Match 87"
  },
  {
    "id": "match-097",
    "phase": "quarterfinal",
    "phaseLabel": "Cuartos",
    "group": null,
    "date": "2026-07-09",
    "datetime": "2026-07-09T20:00:00Z",
    "venue": "Gillette Stadium, Boston",
    "home": "Ganador partido 89",
    "away": "Ganador partido 90",
    "homeRaw": "Winner Match 89",
    "awayRaw": "Winner Match 90"
  },
  {
    "id": "match-098",
    "phase": "quarterfinal",
    "phaseLabel": "Cuartos",
    "group": null,
    "date": "2026-07-10",
    "datetime": "2026-07-10T19:00:00Z",
    "venue": "SoFi Stadium, Los Ángeles",
    "home": "Ganador partido 93",
    "away": "Ganador partido 94",
    "homeRaw": "Winner Match 93",
    "awayRaw": "Winner Match 94"
  },
  {
    "id": "match-099",
    "phase": "quarterfinal",
    "phaseLabel": "Cuartos",
    "group": null,
    "date": "2026-07-11",
    "datetime": "2026-07-11T21:00:00Z",
    "venue": "Hard Rock Stadium, Miami",
    "home": "Ganador partido 91",
    "away": "Ganador partido 92",
    "homeRaw": "Winner Match 91",
    "awayRaw": "Winner Match 92"
  },
  {
    "id": "match-100",
    "phase": "quarterfinal",
    "phaseLabel": "Cuartos",
    "group": null,
    "date": "2026-07-11",
    "datetime": "2026-07-12T01:00:00Z",
    "venue": "Arrowhead Stadium, Kansas City",
    "home": "Ganador partido 95",
    "away": "Ganador partido 96",
    "homeRaw": "Winner Match 95",
    "awayRaw": "Winner Match 96"
  },
  {
    "id": "match-101",
    "phase": "semifinal",
    "phaseLabel": "Semifinal",
    "group": null,
    "date": "2026-07-14",
    "datetime": "2026-07-14T19:00:00Z",
    "venue": "AT&T Stadium, Dallas",
    "home": "Ganador partido 97",
    "away": "Ganador partido 98",
    "homeRaw": "Winner Match 97",
    "awayRaw": "Winner Match 98"
  },
  {
    "id": "match-102",
    "phase": "semifinal",
    "phaseLabel": "Semifinal",
    "group": null,
    "date": "2026-07-15",
    "datetime": "2026-07-15T19:00:00Z",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "home": "Ganador partido 99",
    "away": "Ganador partido 100",
    "homeRaw": "Winner Match 99",
    "awayRaw": "Winner Match 100"
  },
  {
    "id": "match-103",
    "phase": "third_place",
    "phaseLabel": "3er Puesto",
    "group": null,
    "date": "2026-07-18",
    "datetime": "2026-07-18T21:00:00Z",
    "venue": "Hard Rock Stadium, Miami",
    "home": "Perdedor partido 101",
    "away": "Perdedor partido 102",
    "homeRaw": "Loser SF-1",
    "awayRaw": "Loser SF-2"
  },
  {
    "id": "match-104",
    "phase": "final",
    "phaseLabel": "Final",
    "group": null,
    "date": "2026-07-19",
    "datetime": "2026-07-19T19:00:00Z",
    "venue": "MetLife Stadium, Nueva York/NJ",
    "home": "Ganador partido 101",
    "away": "Ganador partido 102",
    "homeRaw": "Winner SF-1",
    "awayRaw": "Winner SF-2"
  }
];

export const ALL_TEAMS = [
  "Alemania",
  "Arabia Saudita",
  "Argelia",
  "Argentina",
  "Australia",
  "Austria",
  "Bosnia y Herzegovina",
  "Brasil",
  "Bélgica",
  "Cabo Verde",
  "Canadá",
  "Colombia",
  "Corea del Sur",
  "Costa de Marfil",
  "Croacia",
  "Curazao",
  "Ecuador",
  "Egipto",
  "Escocia",
  "España",
  "Estados Unidos",
  "Francia",
  "Ghana",
  "Haití",
  "Inglaterra",
  "Irak",
  "Irán",
  "Japón",
  "Jordania",
  "Marruecos",
  "México",
  "Noruega",
  "Nueva Zelanda",
  "Panamá",
  "Paraguay",
  "Países Bajos",
  "Portugal",
  "Qatar",
  "RD Congo",
  "República Checa",
  "Senegal",
  "Sudáfrica",
  "Suecia",
  "Suiza",
  "Turquía",
  "Túnez",
  "Uruguay",
  "Uzbekistán"
];
