// Fixture oficial del Mundial 2026 (sorteo del 5/12/2025).
// Datos verificados desde Wikipedia post-sorteo.

export const GROUPS = {
  "A": [
    "México",
    "Sudáfrica",
    "Corea del Sur",
    "República Checa"
  ],
  "B": [
    "Canadá",
    "Bosnia y Herzegovina",
    "Qatar",
    "Suiza"
  ],
  "C": [
    "Brasil",
    "Marruecos",
    "Haití",
    "Escocia"
  ],
  "D": [
    "Estados Unidos",
    "Paraguay",
    "Australia",
    "Turquía"
  ],
  "E": [
    "Alemania",
    "Curazao",
    "Costa de Marfil",
    "Ecuador"
  ],
  "F": [
    "Países Bajos",
    "Japón",
    "Suecia",
    "Túnez"
  ],
  "G": [
    "Bélgica",
    "Egipto",
    "Irán",
    "Nueva Zelanda"
  ],
  "H": [
    "España",
    "Cabo Verde",
    "Arabia Saudita",
    "Uruguay"
  ],
  "I": [
    "Francia",
    "Senegal",
    "Irak",
    "Noruega"
  ],
  "J": [
    "Argentina",
    "Argelia",
    "Austria",
    "Jordania"
  ],
  "K": [
    "Portugal",
    "RD Congo",
    "Uzbekistán",
    "Colombia"
  ],
  "L": [
    "Inglaterra",
    "Croacia",
    "Ghana",
    "Panamá"
  ]
};

export const MATCHES = [
  {
    "id": "match-001",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-11",
    "datetime": "2026-06-11T19:00:00Z",
    "venue": "Estadio Banorte (Azteca), Mexico City",
    "home": "México",
    "away": "Sudáfrica",
    "homeRaw": "Mexico",
    "awayRaw": "South Africa"
  },
  {
    "id": "match-002",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-11",
    "datetime": null,
    "venue": null,
    "home": "Corea del Sur",
    "away": "República Checa",
    "homeRaw": "South Korea",
    "awayRaw": "Czech Republic"
  },
  {
    "id": "match-003",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-12",
    "datetime": null,
    "venue": "BMO Field, Toronto",
    "home": "Canadá",
    "away": "Bosnia y Herzegovina",
    "homeRaw": "Canada",
    "awayRaw": "Bosnia and Herzegovina"
  },
  {
    "id": "match-004",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-12",
    "datetime": null,
    "venue": null,
    "home": "Qatar",
    "away": "Suiza",
    "homeRaw": "Qatar",
    "awayRaw": "Switzerland"
  },
  {
    "id": "match-005",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-12",
    "datetime": null,
    "venue": "SoFi Stadium, Los Angeles",
    "home": "Estados Unidos",
    "away": "Paraguay",
    "homeRaw": "United States",
    "awayRaw": "Paraguay"
  },
  {
    "id": "match-006",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-12",
    "datetime": null,
    "venue": null,
    "home": "Australia",
    "away": "Turquía",
    "homeRaw": "Australia",
    "awayRaw": "Turkey"
  },
  {
    "id": "match-007",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-13",
    "datetime": null,
    "venue": null,
    "home": "Brasil",
    "away": "Marruecos",
    "homeRaw": "Brazil",
    "awayRaw": "Morocco"
  },
  {
    "id": "match-008",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-13",
    "datetime": null,
    "venue": null,
    "home": "Haití",
    "away": "Escocia",
    "homeRaw": "Haiti",
    "awayRaw": "Scotland"
  },
  {
    "id": "match-009",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-14",
    "datetime": null,
    "venue": null,
    "home": "Alemania",
    "away": "Curazao",
    "homeRaw": "Germany",
    "awayRaw": "Curacao"
  },
  {
    "id": "match-010",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-14",
    "datetime": null,
    "venue": null,
    "home": "Costa de Marfil",
    "away": "Ecuador",
    "homeRaw": "Ivory Coast",
    "awayRaw": "Ecuador"
  },
  {
    "id": "match-011",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-14",
    "datetime": null,
    "venue": null,
    "home": "Países Bajos",
    "away": "Japón",
    "homeRaw": "Netherlands",
    "awayRaw": "Japan"
  },
  {
    "id": "match-012",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-14",
    "datetime": null,
    "venue": null,
    "home": "Suecia",
    "away": "Túnez",
    "homeRaw": "Sweden",
    "awayRaw": "Tunisia"
  },
  {
    "id": "match-013",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-15",
    "datetime": null,
    "venue": null,
    "home": "Bélgica",
    "away": "Egipto",
    "homeRaw": "Belgium",
    "awayRaw": "Egypt"
  },
  {
    "id": "match-014",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-15",
    "datetime": null,
    "venue": null,
    "home": "Irán",
    "away": "Nueva Zelanda",
    "homeRaw": "Iran",
    "awayRaw": "New Zealand"
  },
  {
    "id": "match-015",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-15",
    "datetime": null,
    "venue": null,
    "home": "España",
    "away": "Cabo Verde",
    "homeRaw": "Spain",
    "awayRaw": "Cape Verde"
  },
  {
    "id": "match-016",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-15",
    "datetime": null,
    "venue": null,
    "home": "Arabia Saudita",
    "away": "Uruguay",
    "homeRaw": "Saudi Arabia",
    "awayRaw": "Uruguay"
  },
  {
    "id": "match-017",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-16",
    "datetime": null,
    "venue": null,
    "home": "Francia",
    "away": "Senegal",
    "homeRaw": "France",
    "awayRaw": "Senegal"
  },
  {
    "id": "match-018",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-16",
    "datetime": null,
    "venue": null,
    "home": "Irak",
    "away": "Noruega",
    "homeRaw": "Iraq",
    "awayRaw": "Norway"
  },
  {
    "id": "match-019",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-16",
    "datetime": null,
    "venue": null,
    "home": "Argentina",
    "away": "Argelia",
    "homeRaw": "Argentina",
    "awayRaw": "Algeria"
  },
  {
    "id": "match-020",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-16",
    "datetime": null,
    "venue": null,
    "home": "Austria",
    "away": "Jordania",
    "homeRaw": "Austria",
    "awayRaw": "Jordan"
  },
  {
    "id": "match-021",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-17",
    "datetime": null,
    "venue": null,
    "home": "Portugal",
    "away": "RD Congo",
    "homeRaw": "Portugal",
    "awayRaw": "DR Congo"
  },
  {
    "id": "match-022",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-17",
    "datetime": null,
    "venue": null,
    "home": "Uzbekistán",
    "away": "Colombia",
    "homeRaw": "Uzbekistan",
    "awayRaw": "Colombia"
  },
  {
    "id": "match-023",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-17",
    "datetime": null,
    "venue": null,
    "home": "Inglaterra",
    "away": "Croacia",
    "homeRaw": "England",
    "awayRaw": "Croatia"
  },
  {
    "id": "match-024",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-17",
    "datetime": null,
    "venue": null,
    "home": "Ghana",
    "away": "Panamá",
    "homeRaw": "Ghana",
    "awayRaw": "Panama"
  },
  {
    "id": "match-025",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-18",
    "datetime": null,
    "venue": null,
    "home": "México",
    "away": "Corea del Sur",
    "homeRaw": "Mexico",
    "awayRaw": "South Korea"
  },
  {
    "id": "match-026",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-18",
    "datetime": null,
    "venue": null,
    "home": "República Checa",
    "away": "Sudáfrica",
    "homeRaw": "Czech Republic",
    "awayRaw": "South Africa"
  },
  {
    "id": "match-027",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-18",
    "datetime": null,
    "venue": null,
    "home": "Canadá",
    "away": "Qatar",
    "homeRaw": "Canada",
    "awayRaw": "Qatar"
  },
  {
    "id": "match-028",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-18",
    "datetime": null,
    "venue": null,
    "home": "Suiza",
    "away": "Bosnia y Herzegovina",
    "homeRaw": "Switzerland",
    "awayRaw": "Bosnia and Herzegovina"
  },
  {
    "id": "match-029",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-19",
    "datetime": null,
    "venue": null,
    "home": "Brasil",
    "away": "Haití",
    "homeRaw": "Brazil",
    "awayRaw": "Haiti"
  },
  {
    "id": "match-030",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-19",
    "datetime": null,
    "venue": null,
    "home": "Escocia",
    "away": "Marruecos",
    "homeRaw": "Scotland",
    "awayRaw": "Morocco"
  },
  {
    "id": "match-031",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-19",
    "datetime": null,
    "venue": null,
    "home": "Estados Unidos",
    "away": "Australia",
    "homeRaw": "United States",
    "awayRaw": "Australia"
  },
  {
    "id": "match-032",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-19",
    "datetime": null,
    "venue": null,
    "home": "Turquía",
    "away": "Paraguay",
    "homeRaw": "Turkey",
    "awayRaw": "Paraguay"
  },
  {
    "id": "match-033",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-20",
    "datetime": null,
    "venue": null,
    "home": "Alemania",
    "away": "Costa de Marfil",
    "homeRaw": "Germany",
    "awayRaw": "Ivory Coast"
  },
  {
    "id": "match-034",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-20",
    "datetime": null,
    "venue": null,
    "home": "Ecuador",
    "away": "Curazao",
    "homeRaw": "Ecuador",
    "awayRaw": "Curacao"
  },
  {
    "id": "match-035",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-20",
    "datetime": null,
    "venue": null,
    "home": "Países Bajos",
    "away": "Suecia",
    "homeRaw": "Netherlands",
    "awayRaw": "Sweden"
  },
  {
    "id": "match-036",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-20",
    "datetime": null,
    "venue": null,
    "home": "Túnez",
    "away": "Japón",
    "homeRaw": "Tunisia",
    "awayRaw": "Japan"
  },
  {
    "id": "match-037",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-21",
    "datetime": null,
    "venue": null,
    "home": "Bélgica",
    "away": "Irán",
    "homeRaw": "Belgium",
    "awayRaw": "Iran"
  },
  {
    "id": "match-038",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-21",
    "datetime": null,
    "venue": null,
    "home": "Nueva Zelanda",
    "away": "Egipto",
    "homeRaw": "New Zealand",
    "awayRaw": "Egypt"
  },
  {
    "id": "match-039",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-21",
    "datetime": null,
    "venue": null,
    "home": "España",
    "away": "Arabia Saudita",
    "homeRaw": "Spain",
    "awayRaw": "Saudi Arabia"
  },
  {
    "id": "match-040",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-21",
    "datetime": null,
    "venue": null,
    "home": "Uruguay",
    "away": "Cabo Verde",
    "homeRaw": "Uruguay",
    "awayRaw": "Cape Verde"
  },
  {
    "id": "match-041",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-22",
    "datetime": null,
    "venue": null,
    "home": "Francia",
    "away": "Irak",
    "homeRaw": "France",
    "awayRaw": "Iraq"
  },
  {
    "id": "match-042",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-22",
    "datetime": null,
    "venue": null,
    "home": "Noruega",
    "away": "Senegal",
    "homeRaw": "Norway",
    "awayRaw": "Senegal"
  },
  {
    "id": "match-043",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-22",
    "datetime": null,
    "venue": null,
    "home": "Argentina",
    "away": "Austria",
    "homeRaw": "Argentina",
    "awayRaw": "Austria"
  },
  {
    "id": "match-044",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-22",
    "datetime": null,
    "venue": null,
    "home": "Jordania",
    "away": "Argelia",
    "homeRaw": "Jordan",
    "awayRaw": "Algeria"
  },
  {
    "id": "match-045",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-23",
    "datetime": null,
    "venue": null,
    "home": "Portugal",
    "away": "Uzbekistán",
    "homeRaw": "Portugal",
    "awayRaw": "Uzbekistan"
  },
  {
    "id": "match-046",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-23",
    "datetime": null,
    "venue": null,
    "home": "Colombia",
    "away": "RD Congo",
    "homeRaw": "Colombia",
    "awayRaw": "DR Congo"
  },
  {
    "id": "match-047",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-23",
    "datetime": null,
    "venue": null,
    "home": "Inglaterra",
    "away": "Ghana",
    "homeRaw": "England",
    "awayRaw": "Ghana"
  },
  {
    "id": "match-048",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-23",
    "datetime": null,
    "venue": null,
    "home": "Panamá",
    "away": "Croacia",
    "homeRaw": "Panama",
    "awayRaw": "Croatia"
  },
  {
    "id": "match-049",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-24",
    "datetime": null,
    "venue": null,
    "home": "República Checa",
    "away": "México",
    "homeRaw": "Czech Republic",
    "awayRaw": "Mexico"
  },
  {
    "id": "match-050",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "A",
    "date": "2026-06-24",
    "datetime": null,
    "venue": null,
    "home": "Sudáfrica",
    "away": "Corea del Sur",
    "homeRaw": "South Africa",
    "awayRaw": "South Korea"
  },
  {
    "id": "match-051",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-24",
    "datetime": null,
    "venue": null,
    "home": "Suiza",
    "away": "Canadá",
    "homeRaw": "Switzerland",
    "awayRaw": "Canada"
  },
  {
    "id": "match-052",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "B",
    "date": "2026-06-24",
    "datetime": null,
    "venue": null,
    "home": "Bosnia y Herzegovina",
    "away": "Qatar",
    "homeRaw": "Bosnia and Herzegovina",
    "awayRaw": "Qatar"
  },
  {
    "id": "match-053",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-24",
    "datetime": null,
    "venue": null,
    "home": "Escocia",
    "away": "Brasil",
    "homeRaw": "Scotland",
    "awayRaw": "Brazil"
  },
  {
    "id": "match-054",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "C",
    "date": "2026-06-24",
    "datetime": null,
    "venue": null,
    "home": "Marruecos",
    "away": "Haití",
    "homeRaw": "Morocco",
    "awayRaw": "Haiti"
  },
  {
    "id": "match-055",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-25",
    "datetime": null,
    "venue": null,
    "home": "Turquía",
    "away": "Estados Unidos",
    "homeRaw": "Turkey",
    "awayRaw": "United States"
  },
  {
    "id": "match-056",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "D",
    "date": "2026-06-25",
    "datetime": null,
    "venue": null,
    "home": "Paraguay",
    "away": "Australia",
    "homeRaw": "Paraguay",
    "awayRaw": "Australia"
  },
  {
    "id": "match-057",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-25",
    "datetime": null,
    "venue": null,
    "home": "Ecuador",
    "away": "Alemania",
    "homeRaw": "Ecuador",
    "awayRaw": "Germany"
  },
  {
    "id": "match-058",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "E",
    "date": "2026-06-25",
    "datetime": null,
    "venue": null,
    "home": "Curazao",
    "away": "Costa de Marfil",
    "homeRaw": "Curacao",
    "awayRaw": "Ivory Coast"
  },
  {
    "id": "match-059",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-25",
    "datetime": null,
    "venue": null,
    "home": "Túnez",
    "away": "Países Bajos",
    "homeRaw": "Tunisia",
    "awayRaw": "Netherlands"
  },
  {
    "id": "match-060",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "F",
    "date": "2026-06-25",
    "datetime": null,
    "venue": null,
    "home": "Japón",
    "away": "Suecia",
    "homeRaw": "Japan",
    "awayRaw": "Sweden"
  },
  {
    "id": "match-061",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-26",
    "datetime": null,
    "venue": null,
    "home": "Nueva Zelanda",
    "away": "Bélgica",
    "homeRaw": "New Zealand",
    "awayRaw": "Belgium"
  },
  {
    "id": "match-062",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "G",
    "date": "2026-06-26",
    "datetime": null,
    "venue": null,
    "home": "Egipto",
    "away": "Irán",
    "homeRaw": "Egypt",
    "awayRaw": "Iran"
  },
  {
    "id": "match-063",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-26",
    "datetime": null,
    "venue": null,
    "home": "Uruguay",
    "away": "España",
    "homeRaw": "Uruguay",
    "awayRaw": "Spain"
  },
  {
    "id": "match-064",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "H",
    "date": "2026-06-26",
    "datetime": null,
    "venue": null,
    "home": "Cabo Verde",
    "away": "Arabia Saudita",
    "homeRaw": "Cape Verde",
    "awayRaw": "Saudi Arabia"
  },
  {
    "id": "match-065",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-26",
    "datetime": null,
    "venue": null,
    "home": "Noruega",
    "away": "Francia",
    "homeRaw": "Norway",
    "awayRaw": "France"
  },
  {
    "id": "match-066",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "I",
    "date": "2026-06-26",
    "datetime": null,
    "venue": null,
    "home": "Senegal",
    "away": "Irak",
    "homeRaw": "Senegal",
    "awayRaw": "Iraq"
  },
  {
    "id": "match-067",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-27",
    "datetime": null,
    "venue": null,
    "home": "Jordania",
    "away": "Argentina",
    "homeRaw": "Jordan",
    "awayRaw": "Argentina"
  },
  {
    "id": "match-068",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "J",
    "date": "2026-06-27",
    "datetime": null,
    "venue": null,
    "home": "Argelia",
    "away": "Austria",
    "homeRaw": "Algeria",
    "awayRaw": "Austria"
  },
  {
    "id": "match-069",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-27",
    "datetime": null,
    "venue": null,
    "home": "Colombia",
    "away": "Portugal",
    "homeRaw": "Colombia",
    "awayRaw": "Portugal"
  },
  {
    "id": "match-070",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "K",
    "date": "2026-06-27",
    "datetime": null,
    "venue": null,
    "home": "RD Congo",
    "away": "Uzbekistán",
    "homeRaw": "DR Congo",
    "awayRaw": "Uzbekistan"
  },
  {
    "id": "match-071",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-27",
    "datetime": null,
    "venue": null,
    "home": "Panamá",
    "away": "Inglaterra",
    "homeRaw": "Panama",
    "awayRaw": "England"
  },
  {
    "id": "match-072",
    "phase": "group",
    "phaseLabel": "Grupos",
    "group": "L",
    "date": "2026-06-27",
    "datetime": null,
    "venue": null,
    "home": "Croacia",
    "away": "Ghana",
    "homeRaw": "Croatia",
    "awayRaw": "Ghana"
  },
  {
    "id": "match-073",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-28",
    "datetime": null,
    "venue": null,
    "home": "1° Grupo A",
    "away": "Mejor 3° (C/D/E/F)",
    "homeRaw": "Winner Group A",
    "awayRaw": "Best Third (C/D/E/F)"
  },
  {
    "id": "match-074",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-28",
    "datetime": null,
    "venue": null,
    "home": "2° Grupo C",
    "away": "2° Grupo F",
    "homeRaw": "Runner-up Group C",
    "awayRaw": "Runner-up Group F"
  },
  {
    "id": "match-075",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-29",
    "datetime": null,
    "venue": null,
    "home": "1° Grupo B",
    "away": "Mejor 3° (A/E/F/I)",
    "homeRaw": "Winner Group B",
    "awayRaw": "Best Third (A/E/F/I)"
  },
  {
    "id": "match-076",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-29",
    "datetime": null,
    "venue": null,
    "home": "2° Grupo A",
    "away": "2° Grupo D",
    "homeRaw": "Runner-up Group A",
    "awayRaw": "Runner-up Group D"
  },
  {
    "id": "match-077",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-29",
    "datetime": null,
    "venue": null,
    "home": "1° Grupo D",
    "away": "Mejor 3° (B/E/F)",
    "homeRaw": "Winner Group D",
    "awayRaw": "Best Third (B/E/F)"
  },
  {
    "id": "match-078",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-29",
    "datetime": null,
    "venue": null,
    "home": "1° Grupo E",
    "away": "Mejor 3° (A/B/C/D)",
    "homeRaw": "Winner Group E",
    "awayRaw": "Best Third (A/B/C/D)"
  },
  {
    "id": "match-079",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-30",
    "datetime": null,
    "venue": null,
    "home": "2° Grupo K",
    "away": "2° Grupo L",
    "homeRaw": "Runner-up Group K",
    "awayRaw": "Runner-up Group L"
  },
  {
    "id": "match-080",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-30",
    "datetime": null,
    "venue": null,
    "home": "1° Grupo L",
    "away": "Mejor 3° (E/H/I/J)",
    "homeRaw": "Winner Group L",
    "awayRaw": "Best Third (E/H/I/J)"
  },
  {
    "id": "match-081",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-06-30",
    "datetime": null,
    "venue": null,
    "home": "2° Grupo H",
    "away": "2° Grupo I",
    "homeRaw": "Runner-up Group H",
    "awayRaw": "Runner-up Group I"
  },
  {
    "id": "match-082",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-01",
    "datetime": null,
    "venue": null,
    "home": "1° Grupo G",
    "away": "Mejor 3° (A/B/C/D)",
    "homeRaw": "Winner Group G",
    "awayRaw": "Best Third (A/B/C/D)"
  },
  {
    "id": "match-083",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-01",
    "datetime": null,
    "venue": null,
    "home": "2° Grupo E",
    "away": "2° Grupo J",
    "homeRaw": "Runner-up Group E",
    "awayRaw": "Runner-up Group J"
  },
  {
    "id": "match-084",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-01",
    "datetime": null,
    "venue": null,
    "home": "1° Grupo I",
    "away": "Mejor 3° (B/E/F)",
    "homeRaw": "Winner Group I",
    "awayRaw": "Best Third (B/E/F)"
  },
  {
    "id": "match-085",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-02",
    "datetime": null,
    "venue": null,
    "home": "2° Grupo B",
    "away": "2° Grupo G",
    "homeRaw": "Runner-up Group B",
    "awayRaw": "Runner-up Group G"
  },
  {
    "id": "match-086",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-02",
    "datetime": null,
    "venue": null,
    "home": "1° Grupo K",
    "away": "Mejor 3° (G/H/I/J)",
    "homeRaw": "Winner Group K",
    "awayRaw": "Best Third (G/H/I/J)"
  },
  {
    "id": "match-087",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-03",
    "datetime": null,
    "venue": null,
    "home": "1° Grupo H",
    "away": "Mejor 3° (A/B/F/G)",
    "homeRaw": "Winner Group H",
    "awayRaw": "Best Third (A/B/F/G)"
  },
  {
    "id": "match-088",
    "phase": "round_of_32",
    "phaseLabel": "16vos",
    "group": null,
    "date": "2026-07-03",
    "datetime": null,
    "venue": null,
    "home": "1° Grupo J",
    "away": "Mejor 3° (A/B/F/G)",
    "homeRaw": "Winner Group J",
    "awayRaw": "Best Third (A/B/F/G)"
  },
  {
    "id": "match-089",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-04",
    "datetime": null,
    "venue": null,
    "home": "Ganador R32-1",
    "away": "Ganador R32-2",
    "homeRaw": "Winner R32-1",
    "awayRaw": "Winner R32-2"
  },
  {
    "id": "match-090",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-04",
    "datetime": null,
    "venue": null,
    "home": "Ganador R32-3",
    "away": "Ganador R32-4",
    "homeRaw": "Winner R32-3",
    "awayRaw": "Winner R32-4"
  },
  {
    "id": "match-091",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-05",
    "datetime": null,
    "venue": null,
    "home": "Ganador R32-5",
    "away": "Ganador R32-6",
    "homeRaw": "Winner R32-5",
    "awayRaw": "Winner R32-6"
  },
  {
    "id": "match-092",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-05",
    "datetime": null,
    "venue": null,
    "home": "Ganador R32-7",
    "away": "Ganador R32-8",
    "homeRaw": "Winner R32-7",
    "awayRaw": "Winner R32-8"
  },
  {
    "id": "match-093",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-06",
    "datetime": null,
    "venue": null,
    "home": "Ganador R32-9",
    "away": "Ganador R32-10",
    "homeRaw": "Winner R32-9",
    "awayRaw": "Winner R32-10"
  },
  {
    "id": "match-094",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-06",
    "datetime": null,
    "venue": null,
    "home": "Ganador R32-11",
    "away": "Ganador R32-12",
    "homeRaw": "Winner R32-11",
    "awayRaw": "Winner R32-12"
  },
  {
    "id": "match-095",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-07",
    "datetime": null,
    "venue": null,
    "home": "Ganador R32-13",
    "away": "Ganador R32-14",
    "homeRaw": "Winner R32-13",
    "awayRaw": "Winner R32-14"
  },
  {
    "id": "match-096",
    "phase": "round_of_16",
    "phaseLabel": "Octavos",
    "group": null,
    "date": "2026-07-07",
    "datetime": null,
    "venue": null,
    "home": "Ganador R32-15",
    "away": "Ganador R32-16",
    "homeRaw": "Winner R32-15",
    "awayRaw": "Winner R32-16"
  },
  {
    "id": "match-097",
    "phase": "quarterfinal",
    "phaseLabel": "Cuartos",
    "group": null,
    "date": "2026-07-09",
    "datetime": null,
    "venue": null,
    "home": "Ganador OF-1",
    "away": "Ganador OF-2",
    "homeRaw": "Winner R16-1",
    "awayRaw": "Winner R16-2"
  },
  {
    "id": "match-098",
    "phase": "quarterfinal",
    "phaseLabel": "Cuartos",
    "group": null,
    "date": "2026-07-10",
    "datetime": null,
    "venue": null,
    "home": "Ganador OF-3",
    "away": "Ganador OF-4",
    "homeRaw": "Winner R16-3",
    "awayRaw": "Winner R16-4"
  },
  {
    "id": "match-099",
    "phase": "quarterfinal",
    "phaseLabel": "Cuartos",
    "group": null,
    "date": "2026-07-11",
    "datetime": null,
    "venue": null,
    "home": "Ganador OF-5",
    "away": "Ganador OF-6",
    "homeRaw": "Winner R16-5",
    "awayRaw": "Winner R16-6"
  },
  {
    "id": "match-100",
    "phase": "quarterfinal",
    "phaseLabel": "Cuartos",
    "group": null,
    "date": "2026-07-11",
    "datetime": null,
    "venue": null,
    "home": "Ganador OF-7",
    "away": "Ganador OF-8",
    "homeRaw": "Winner R16-7",
    "awayRaw": "Winner R16-8"
  },
  {
    "id": "match-101",
    "phase": "semifinal",
    "phaseLabel": "Semifinal",
    "group": null,
    "date": "2026-07-14",
    "datetime": null,
    "venue": null,
    "home": "Ganador CF-1",
    "away": "Ganador CF-2",
    "homeRaw": "Winner QF-1",
    "awayRaw": "Winner QF-2"
  },
  {
    "id": "match-102",
    "phase": "semifinal",
    "phaseLabel": "Semifinal",
    "group": null,
    "date": "2026-07-15",
    "datetime": null,
    "venue": null,
    "home": "Ganador CF-3",
    "away": "Ganador CF-4",
    "homeRaw": "Winner QF-3",
    "awayRaw": "Winner QF-4"
  },
  {
    "id": "match-103",
    "phase": "third_place",
    "phaseLabel": "3er Puesto",
    "group": null,
    "date": "2026-07-18",
    "datetime": null,
    "venue": null,
    "home": "Perdedor SF-1",
    "away": "Perdedor SF-2",
    "homeRaw": "Loser SF-1",
    "awayRaw": "Loser SF-2"
  },
  {
    "id": "match-104",
    "phase": "final",
    "phaseLabel": "Final",
    "group": null,
    "date": "2026-07-19",
    "datetime": "2026-07-19T21:00:00Z",
    "venue": "MetLife Stadium, New York/New Jersey",
    "home": "Ganador SF-1",
    "away": "Ganador SF-2",
    "homeRaw": "Winner SF-1",
    "awayRaw": "Winner SF-2"
  }
];

export const ALL_TEAMS = [
  "Alemania",
  "Arabia Saudita",
  "Argelia",
  "Argentina",
  "Australia",
  "Austria",
  "Bosnia y Herzegovina",
  "Brasil",
  "Bélgica",
  "Cabo Verde",
  "Canadá",
  "Colombia",
  "Corea del Sur",
  "Costa de Marfil",
  "Croacia",
  "Curazao",
  "Ecuador",
  "Egipto",
  "Escocia",
  "España",
  "Estados Unidos",
  "Francia",
  "Ghana",
  "Haití",
  "Inglaterra",
  "Irak",
  "Irán",
  "Japón",
  "Jordania",
  "Marruecos",
  "México",
  "Noruega",
  "Nueva Zelanda",
  "Panamá",
  "Paraguay",
  "Países Bajos",
  "Portugal",
  "Qatar",
  "RD Congo",
  "República Checa",
  "Senegal",
  "Sudáfrica",
  "Suecia",
  "Suiza",
  "Turquía",
  "Túnez",
  "Uruguay",
  "Uzbekistán"
];
